---
title: "Translocation"
author: "Scott Coffin"
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(caret)
library(DALEX)
library(skimr)
library(ggeffects)
#library(ggdark)
```
# Setup
```{r}
#data cleanup
Tissue_Translocation <- read_excel("translocation/Tissue_Translocation.xlsx", 
    sheet = "obs") %>% 
  mutate(Species = as.factor(Species)) %>% 
  mutate(Polymer = as.factor(Polymer)) %>% 
  mutate(lab.field = as.factor(lab.field)) %>% 
  mutate(Shape = as.factor(Shape)) %>%
  mutate(size.um = `Size (µm)`) %>% 
  mutate(size.nm = size.um * 1000) %>% 
  mutate(Organisms = as.factor(Organisms)) %>%
  mutate(Exposure_route = as.factor(Exposure_route)) %>% 
  mutate(Tissue = as.factor(Tissue)) %>% 
  mutate(translocated_10 = case_when(`Tissue translocation observed (Y/N)` == "Y" ~ 1,
                                     `Tissue translocation observed (Y/N)` == "N" ~ 0))

#select variables for model
df <- Tissue_Translocation %>% 
  select(c(translocated_10,
           Polymer,
           Shape,
           size.um,
           Organisms,
           lab.field,
           Exposure_route
           )) %>% 
  drop_na()
skim(df)
```
## Join
```{r}
#Load aoc_z into dataframe. This file is generated from RDA_Maker.R
#Source("Tox Data/RDA_Maker.R")
aoc_z <- readRDS(file = "Tox Data/aoc_z.Rda")
```
```{r}
quality <- aoc_z %>% 
 select(c(
    doi:risk.tier.zero.criteria.failure
  ))

joined <- left_join(Tissue_Translocation, quality, by = "doi") %>% 
  distinct() %>% 
     #Assign descriptions to each criteria
      rename("Test Medium Reported*" = "tech.a1",
    "Administration Route Reported*" = "tech.a2",
     "Test Species Reported*" = "tech.a3",
     "Sample Size Reported*" = "tech.a4",
    "Control Group Reported*" = "tech.a5",
    "Exposure Duration Reported*" = "tech.a6" ,
    "Particle Size*" = "tech.1",
    "Particle Shape*" = "tech.2",
    "Polymer Type*" = "tech.3",
                                  "Source of Microplastics*" = "tech.4",
                                     "Data Reporting*" = "tech.5",
                                    "Chemical Purity" = "tech.6",
                                     "Laboratory Preparation" = "tech.7",
                                    "Background Contamination" = "tech.8",
                                    "Exposure Verification" = "tech.9",
                                     "Exposure Homogeneity" = "tech.10",
                                    "Exposure Assessment" = "tech.11",
                                    "Replication" = "tech.12",
                                    "Endpoints" = "risk.13",
                                    "Food Availability" = "risk.14",
                                    "Effect Thresholds" = "risk.15",
                                    "Dose Response" = "risk.16",
                                    "Concentration Range" = "risk.17",
                                    "Aging and Biofouling" = "risk.18",
                                    "Risk Assessment" = "risk.18",
                                    "Microplastic Diversity" = "risk.19",
                                    "Exposure Time" = "risk.20")
 
# what studies are missing quality criteria?
joined %>% filter(is.na('Test Medium Reported*')) %>% 
  distinct(doi, .keep_all = TRUE) %>% 
  view()

write.csv(joined, "translocation/translocation_scored_2.csv")

# #re-assign descriptions to each criteria in normal format
#       rename("tech.a1" = "Test Medium Reported*",
#     "tech.a2" = "Administration Route Reported*",
#      "tech.a3" = "Test Species Reported*",
#      "tech.a4" = "Sample Size Reported*",
#     "tech.a5" = "Control Group Reported*",
#     "tech.a6" = "Exposure Duration Reported*",
#     "tech.1" = "Particle Size*",
#     "tech.2" = "Particle Shape*",
#     "tech.3" = "Polymer Type*",
#                                   "tech.4" = "Source of Microplastics*",
#                                     "tech.5" = "Data Reporting*",
#                                     "tech.6" = "Chemical Purity",
#                                     "tech.7" = "Laboratory Preparation",
#                                     "tech.8" = "Background Contamination",
#                                     "tech.9" = "Exposure Verification",
#                                     "tech.10" = "Exposure Homogeneity",
#                                     "tech.11" = "Exposure Assessment",
#                                     "tech.12" = "Replication",
#                                     "risk.13" = "Endpoints",
#                                     "risk.14" = "Food Availability",
#                                     "risk.15" = "Effect Thresholds",
#                                     "risk.16" = "Dose Response",
#                                     "risk.17" = "Concentration Range",
#                                     "risk.18" = "Aging and Biofouling",
#                                     "risk.18" = "Risk Assessment",
#                                     "risk.19" = "Microplastic Diversity",
#                                     "risk.20" = "Exposure Time")
```

```{r}
#histogram
histogram <- Tissue_Translocation %>%  
  ggplot(aes(x = size.um)) + 
  geom_histogram(bins = 20) + 
  scale_x_log10(name = expression(paste("Particle Length (", mu, "m)")),                                                                                               labels = scales::label_comma()) +
  theme_bw()
histogram
```
```{r}

ggsave(filename = "translocation_histogram.jpeg",
       path = "./Concentration data/Threshold_Manuscript_Figs/", 
       plot =histogram, width = 5, height = 3, units = "in",
       bg = "white")
```

```{r}
skim(joined)
```

## Quality Screening


# Modelling
```{r}
translocation_glm <- Tissue_Translocation %>% 
ggplot(aes(x = size.um, y = translocated_10)) +
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE,
              color = "black") +
  scale_x_log10(name = expression(paste("Particle Length (", mu, "m)")),
                labels = scales::label_comma()
                ) +#,
  #n.breaks = 10) +
  scale_y_continuous(name = "Particle Translocation Probability",
                     labels = scales::percent, limits = c(0,1)) +
  theme_classic()
translocation_glm
```

#### Manuscript Figure
```{r}
ggsave(filename = "translocation_glm.jpeg",
       path = "./Concentration data/Threshold_Manuscript_Figs/", 
       plot = translocation_glm, width = 5, height = 5, units = "in",
       bg = "white")
```

##logistic regression
```{r}
response <- as.numeric(as.character(df$translocated_10))
predictors <- as.data.frame(df %>% dplyr::select(-translocated_10))
#build glm
glm_model <- train(translocated_10~., data = df, method = "glm", family = "binomial")
#build explainer for easy interpretation
explainer_glm_model <- DALEX::explain(glm_model, label = "glm", data = predictors, y = response)

#classifier plot
classif_glm <- model_parts(explainer_glm_model, loss_function = loss_root_mean_square)
#plot classifier
plot(classif_glm)
```

```{r}
#partial dependence plot by dose
pdp_classif_glm  <- model_profile(explainer_glm_model, variable = "Polymer", type = "partial")
#partial dependence plot by particle surface area
pdp_classif_glm_2  <- model_profile(explainer_glm_model, variable = "Shape", type = "partial")
#partial dependence plot by particle length
pdp_classif_glm_length  <- model_profile(explainer_glm_model, variable = "size.um", type = "partial")
#partial dependence plot by polymer
pdp_classif_glm_polymer  <- model_profile(explainer_glm_model, variable = "Organisms", type = "partial")

plot(pdp_classif_glm,  pdp_classif_glm_2)

plot(pdp_classif_glm_polymer)
plot(pdp_classif_glm_length)
```
```{r}
summary(glm_model)
```
```{r}
#simpler model
simple <- glm(translocated_10 ~ size.um, data = df, family = "binomial")
summary(simple)

response <- as.numeric(as.character(df$translocated_10))
predictors <- as.data.frame(df %>% dplyr::select(size.um))

#build explainer for easy interpretation
explainer_glm_model <- DALEX::explain(glm_model, label = "glm", data = predictors, y = response)
```
```{r}
explainer_glm_model$model$metric
```


```{r}
library(jtools)
plot_summs(simple, scale = TRUE, inner_ci_level = 0.95, plot.distributions = TRUE)
```
```{r}
export_summs(simple, scale = TRUE,
             error_format = "[{conf.low}, {conf.high}]")
```

```{r}
size.model <- glm(translocated_10 ~ size.um, data = Tissue_Translocation, family = "binomial")
```


```{r}
obj <- ggeffects::ggpredict(simple, terms="size.um [all]")
plot(obj)
```
```{r}
size.model <- glm(translocated_10 ~ size.um, data = Tissue_Translocation, family = "binomial")
#generate distribution of data
mockData <- data.frame(
  size.um = (1:10000))

mockData_fitted <- predict(size.model,
                     mockData,
                     type = "response",
                     se.fit = TRUE) %>% 
  as.data.frame()

mock <- cbind(mockData, mockData_fitted) %>% 
  # model object nanometer has a component called linkinv that 
         # is a function that inverts the link function of the GLM:
  mutate(lower = exp(fit - 1.96 * se.fit)/( 1 + exp(fit - 1.96 * se.fit)),
         upper = exp(fit + 1.96 * se.fit)/( 1 + exp(fit + 1.96 * se.fit)))
  
#plot
translocation_glm <- mock %>% 
  ggplot(aes(x = size.um, 
             y = fit)) +
  geom_line(color = "blue") +
  geom_ribbon(aes(ymin = lower,
                  ymax = upper),
              alpha = 0.5) +
  # geom_point(aes(x = size.nm, y = translocated_10),
  #            data = Tissue_Translocation,
  #            alpha = 0.7) +
   # scale_x_continuous(name = "Particle Length (nm)",
   #                    limits = c(1, 400000),
   #                    breaks = scales::trans_breaks("log10",function(x) 10^x, n = 5),
   #                       labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  scale_x_log10(name = "Particle Length (nm)", #expression(paste("Particle Length (", mu, "m)")),
                limits = c(0, 1000000),
                labels = scales::label_comma()
                ) +#,
  #n.breaks = 10) +
  scale_y_continuous(name = "Particle Translocation Probability",
                     labels = scales::percent, limits = c(0,1)) +
  # labs(title = "Microplastics Particle Translocation",
  #      subtitle = "General Linear Model Output",
  #      caption = "p = 0.034, RMSE = 0.54") +
  #geom_smooth() +
  #scale_color_gradientn(colors = topo.colors(7)) +
  #scale_color_viridis_c(option = "A") +
  theme_bw()
  #dark_theme_bw()
translocation_glm
```





### Model comparison
```{r}
library(jtools)
library(huxtable)
library(flextable)
simple <- lm(translocated_10 ~ size.um, data = df, family = "binomial")
m2 <- lm(translocated_10 ~ Shape, data = df, family = "binomial")
m3 <- lm(translocated_10 ~ Polymer, data = df, family = "binomial")
m4 <- lm(translocated_10 ~ Shape + size.um, data = df, family = "binomial")
m5 <- lm(translocated_10 ~ Shape + size.um + Polymer, data = df, family = "binomial")
m6 <- lm(translocated_10 ~ Shape +  Polymer, data = df, family = "binomial")
full <- glm(translocated_10~., data = df, family = "binomial")


export_summs(simple, m2, m3, m4, scale = TRUE)
```


```{r}
step <- step(full, direction = "both")
summary(step)

```

```{r}
simple <- glm(translocated_10 ~ size.um, data = df, family = "binomial")
summary(simple)
```

